import { test, expect } from "@playwright/test";
import { cp, readFile, rm } from "node:fs/promises";
import path from "node:path";

const fixtureRoot = path.resolve("tests/fixtures/projects");
const projectsRoot = path.resolve("test-results/projects");
const transformValues = (value: string) => value.match(/translate\(([-\d.]+)px, ([-\d.]+)px\) scale\(([-\d.]+)\)/)!.slice(1).map(Number);
const expectTransform = (actual: number[], expected: number[]) => expected.forEach((value, index) => expect(actual[index]).toBeCloseTo(value, 5));

test.beforeEach(async () => {
  await rm(projectsRoot, { recursive: true, force: true });
  await cp(fixtureRoot, projectsRoot, { recursive: true });
});

test("preserves full-image transform when selecting YAML region", async ({ page }) => {
  const errors: string[] = [];
  let putCount = 0;
  page.on("pageerror", (error) => errors.push(error.message));
  page.on("console", (message) => { if (message.type() === "error") errors.push(message.text()); });
  page.on("request", (request) => { if (request.method() === "PUT") putCount += 1; });
  await page.goto("/");
  expect(errors).toEqual([]);
  const initialRegion = (await (await page.request.get("http://localhost:8000/api/projects/scan-01/regions")).json())[0];
  const imageBeforeRotation = await (await page.request.get("http://localhost:8000/api/projects/scan-01/image")).body();
  const root = page.getByRole("treeitem", { name: "scan-01" });
  await expect(root).toHaveAttribute("aria-checked", "true");
  await expect(page.getByRole("heading", { name: "scan-01" })).toBeVisible();
  await expect(page.locator("img.document")).toBeVisible();
  await expect.poll(() => page.locator(".image-window").evaluate((element) => ({ width: element.style.width, height: element.style.height }))).toMatchObject({ width: "1200px", height: "800px" });
  await page.getByRole("button", { name: "Actual Size" }).click();
  const viewer = page.locator(".viewer");
  const imageBox = await page.locator(".image-window").boundingBox();
  const viewerBox = await viewer.boundingBox();
  expect(imageBox).not.toBeNull();
  expect(viewerBox).not.toBeNull();
  const imagePoint = (x: number, y: number) => ({ x: imageBox!.x - viewerBox!.x + x, y: imageBox!.y - viewerBox!.y + y });
  await viewer.hover({ position: imagePoint(120, 100) });
  await page.mouse.down();
  await page.mouse.move(imageBox!.x + 80, imageBox!.y + 70);
  await page.mouse.up();
  await expect(page.locator(".zoom-readout")).toHaveText("100%");
  await viewer.hover({ position: imagePoint(220, 180) });
  await page.mouse.wheel(0, -200);
  await expect(page.locator(".zoom-readout")).toHaveText("112%");
  const transformBeforeRegion = await page.locator(".image-window").evaluate((element) => element.style.transform);
  expect(transformBeforeRegion).toMatch(/^translate\([^)]*\) scale\(1\.12\)$/);
  await page.getByRole("button", { name: /Region/ }).click();
  await page.evaluate(() => new Promise<void>((resolve) => requestAnimationFrame(() => requestAnimationFrame(() => requestAnimationFrame(() => resolve())))));
  await expect(page.getByText("Drag over image to draw region")).toBeVisible();
  await expect(page.locator(".zoom-readout")).toHaveText("112%");
  await expect.poll(() => page.locator(".image-window").evaluate((element) => element.style.transform)).toBe(transformBeforeRegion);
  await page.getByRole("treeitem", { name: "scan-01" }).locator(".tree-project-label").click();
  await expect(page.getByText("Drag over image to draw region")).toHaveCount(0);
  await expect(page.locator(".image-window.crop-window")).toHaveCount(0);
  await page.getByRole("button", { name: /Region/ }).click();
  await expect(page.getByText("Drag over image to draw region")).toBeVisible();
  await page.getByText("Receipt", { exact: true }).click();
  await expect(page.getByText("Drag over image to draw region")).toHaveCount(0);
  await page.evaluate(() => new Promise<void>((resolve) => requestAnimationFrame(() => requestAnimationFrame(() => requestAnimationFrame(() => resolve())))));
  await expect(page.locator(".image-window.crop-window")).toBeVisible();
  await expect.poll(() => page.locator(".image-window.crop-window").evaluate((element) => ({ width: element.style.width, height: element.style.height }))).toMatchObject({ width: "420px", height: "260px" });
  await expect(page.locator("img.document")).toBeVisible();
  const cropFit = await page.evaluate(() => { const viewer = document.querySelector<HTMLElement>(".viewer")!; const scale = Math.max(0.15, Math.min(1, Math.min((viewer.clientWidth - 64) / 420, (viewer.clientHeight - 64) / 260))); return [(viewer.clientWidth - 420 * scale) / 2, (viewer.clientHeight - 260 * scale) / 2, scale]; });
  const cropTransform = await page.locator(".image-window.crop-window").evaluate((element) => element.style.transform);
  expectTransform(transformValues(cropTransform), cropFit);
  expect(cropTransform).not.toBe(transformBeforeRegion);
  const rotate90Request = page.waitForRequest((request) => request.method() === "PUT" && request.url().includes("/regions/1"));
  await page.getByRole("button", { name: "Rotate region right 90 degrees" }).click();
  const rotate90Body = (await rotate90Request).postDataJSON();
  expect(rotate90Body.rotation).toBe(90);
  expect(rotate90Body.rectangle).toEqual(initialRegion.rectangle);
  expect(rotate90Body.name).toBe(initialRegion.name);
  await expect.poll(() => page.locator(".image-surface").evaluate((element) => element.style.transform)).toBe("rotate(90deg)");
  const rotation90Style = await page.locator(".image-window.crop-window").evaluate((element) => ({ width: parseFloat(element.style.width), height: parseFloat(element.style.height) }));
  expect(rotation90Style.width).toBeCloseTo(260, 3);
  expect(rotation90Style.height).toBeCloseTo(420, 3);
  expect(Buffer.compare(imageBeforeRotation, await (await page.request.get("http://localhost:8000/api/projects/scan-01/image")).body())).toBe(0);
  await page.reload();
  await page.getByText("Receipt", { exact: true }).click();
  await expect(page.locator(".image-surface")).toHaveAttribute("style", /rotate\(90deg\)/);
  const putsBeforeStraighten = putCount;
  await page.getByRole("button", { name: "Straighten", exact: true }).click();
  await expect(page.locator(".straighten-cross")).toBeVisible();
  await expect(page.getByRole("slider", { name: "Straighten angle slider" })).toHaveValue("0");
  await expect(page.getByRole("textbox", { name: "Straighten angle" })).toHaveValue("+0.0");
  await page.locator(".straighten-step").last().click();
  await expect(page.getByRole("slider", { name: "Straighten angle slider" })).toHaveValue("0.1");
  await expect(page.getByRole("textbox", { name: "Straighten angle" })).toHaveValue("+0.1");
  await page.locator(".straighten-step").first().click();
  await page.getByRole("textbox", { name: "Straighten angle" }).fill("12.3");
  await page.getByRole("textbox", { name: "Straighten angle" }).press("Enter");
  await expect(page.getByRole("slider", { name: "Straighten angle slider" })).toHaveValue("12.3");
  await expect(page.getByRole("textbox", { name: "Straighten angle" })).toHaveValue("+12.3");
  await expect(page.locator(".image-surface")).toHaveAttribute("style", /rotate\(102\.3deg\)/);
  await page.getByRole("button", { name: "Fit", exact: true }).click();
  await expect(page.locator(".image-surface")).toHaveAttribute("style", /rotate\(102\.3deg\)/);
  const straightenRequest = page.waitForRequest((request) => request.method() === "PUT" && request.url().includes("/regions/1"));
  await page.getByRole("button", { name: "Confirm" }).click();
  const straightenBody = (await straightenRequest).postDataJSON();
  expect(straightenBody.rotation).toBe(90);
  expect(straightenBody.straighten).toBe(12.3);
  expect(straightenBody.rectangle).toEqual(initialRegion.rectangle);
  expect(Buffer.compare(imageBeforeRotation, await (await page.request.get("http://localhost:8000/api/projects/scan-01/image")).body())).toBe(0);
  await page.getByRole("button", { name: "Straighten", exact: true }).click();
  await expect(page.getByRole("slider", { name: "Straighten angle slider" })).toHaveValue("12.3");
  await expect(page.getByRole("textbox", { name: "Straighten angle" })).toHaveValue("+12.3");
  await page.getByRole("button", { name: "Cancel" }).click();
  expect(putCount).toBe(putsBeforeStraighten + 1);
  await page.reload();
  await page.getByText("Receipt", { exact: true }).click();
  await page.getByRole("button", { name: "Fit", exact: true }).click();
  await page.getByRole("button", { name: "Straighten", exact: true }).click();
  await expect(page.getByRole("slider", { name: "Straighten angle slider" })).toHaveValue("12.3");
  await expect(page.locator(".image-surface")).toHaveAttribute("style", /rotate\(102\.3deg\)/);
  await page.getByRole("button", { name: "Cancel", exact: true }).click();
  await page.getByRole("button", { name: "Trim", exact: true }).click();
  const topTrim = page.locator(".trim-control").filter({ hasText: "Top" });
  const leftTrim = page.locator(".trim-control").filter({ hasText: "Left" });
  await expect(topTrim.locator("input")).toHaveValue("0");
  const outerBeforeTrim = await page.locator(".image-window.crop-window").evaluate((element) => ({ width: element.style.width, height: element.style.height }));
  const surfaceBeforeTrim = await page.locator(".image-surface").evaluate((element) => ({ left: element.style.left, top: element.style.top }));
  expect(await page.locator(".image-window.crop-window").evaluate((element) => getComputedStyle(element).overflow)).toBe("hidden");
  expect(await page.locator(".image-surface").evaluate((element) => getComputedStyle(element).overflow)).toBe("hidden");
  await topTrim.locator(".trim-step").last().click();
  await expect(topTrim.locator("input")).toHaveValue("1");
  await topTrim.locator("input").fill("");
  await expect(page.getByRole("button", { name: "Confirm", exact: true })).toBeDisabled();
  await topTrim.locator("input").fill("20");
  await topTrim.locator("input").press("Enter");
  await leftTrim.locator("input").fill("30");
  await leftTrim.locator("input").press("Enter");
  await expect.poll(() => page.locator(".image-window.crop-window").evaluate((element) => ({ width: element.style.width, height: element.style.height }))).not.toEqual(outerBeforeTrim);
  await expect.poll(() => page.locator(".image-surface").evaluate((element) => ({ left: element.style.left, top: element.style.top }))).not.toEqual(surfaceBeforeTrim);
  const trimResponse = page.waitForResponse((response) => response.request().method() === "PUT" && response.url().includes("/regions/1"));
  await page.getByRole("button", { name: "Confirm", exact: true }).click();
  const trimResult = await trimResponse;
  expect(trimResult.status()).toBe(200);
  const trimBody = await trimResult.json();
  expect(trimBody.trim).toEqual({ top: 20, right: 0, bottom: 0, left: 30 });
  expect(trimBody.rectangle).toEqual(initialRegion.rectangle);
  expect(trimBody.rotation).toBe(90);
  expect(trimBody.straighten).toBe(12.3);
  expect(Buffer.compare(imageBeforeRotation, await (await page.request.get("http://localhost:8000/api/projects/scan-01/image")).body())).toBe(0);
  await page.reload();
  await page.getByText("Receipt", { exact: true }).click();
  await page.getByRole("button", { name: "Trim", exact: true }).click();
  await expect(page.locator(".trim-control").filter({ hasText: "Top" }).locator("input")).toHaveValue("20");
  await expect(page.locator(".trim-control").filter({ hasText: "Left" }).locator("input")).toHaveValue("30");
  const persistedTrim = await (await page.request.get("http://localhost:8000/api/projects/scan-01/regions")).json();
  expect(persistedTrim.find((item: { id: number }) => item.id === 1).trim).toEqual({ top: 20, right: 0, bottom: 0, left: 30 });
  expect(persistedTrim.find((item: { id: number }) => item.id === 1).rotation).toBe(90);
  expect(persistedTrim.find((item: { id: number }) => item.id === 1).straighten).toBe(12.3);
  await expect(page.getByRole("button", { name: "Download selected region as PNG" })).toHaveCount(0);
  await page.getByRole("button", { name: "Cancel", exact: true }).click();
  const downloadPromise = page.waitForEvent("download");
  await page.getByRole("button", { name: "Download selected region as PNG" }).click();
  const download = await downloadPromise;
  expect(download.suggestedFilename()).toBe("scan-01-region-1.png");
  const downloadBytes = await readFile((await download.path())!);
  expect(downloadBytes.byteLength).toBeGreaterThan(8);
  expect([...downloadBytes.subarray(0, 8)]).toEqual([137, 80, 78, 71, 13, 10, 26, 10]);
  await page.getByRole("treeitem", { name: "scan-01" }).locator(".tree-project-label").click();
  await expect(page.locator(".image-window.crop-window")).toHaveCount(0);
  const rootFit = await page.evaluate(() => { const viewer = document.querySelector<HTMLElement>(".viewer")!; const scale = Math.max(0.15, Math.min(1, Math.min((viewer.clientWidth - 64) / 1200, (viewer.clientHeight - 64) / 800))); return [(viewer.clientWidth - 1200 * scale) / 2, (viewer.clientHeight - 800 * scale) / 2, scale]; });
  const rootTransform = await page.locator(".image-window").evaluate((element) => element.style.transform);
  expectTransform(transformValues(rootTransform), rootFit);
  await viewer.hover({ position: { x: 30, y: 30 } });
  await page.mouse.down({ button: "middle" });
  await page.mouse.move(94, 78);
  await page.mouse.up({ button: "middle" });
  await expect.poll(() => page.locator(".image-window").evaluate((element) => element.style.transform)).not.toBe(rootTransform);
  await page.getByRole("button", { name: "Edit Receipt" }).click();
  await expect(page.getByRole("button", { name: "Download selected region as PNG" })).toHaveCount(0);
  const editorTransformBeforePan = await page.locator(".image-window").evaluate((element) => element.style.transform);
  const editorDraftSize = await page.locator(".slice-draft > span").textContent();
  const editorViewerBox = await viewer.boundingBox();
  expect(editorViewerBox).not.toBeNull();
  await page.keyboard.down("Space");
  await viewer.hover({ position: { x: 24, y: 24 } });
  await page.mouse.down();
  await page.mouse.move(editorViewerBox!.x + 64, editorViewerBox!.y + 52);
  await page.mouse.up();
  await page.keyboard.up("Space");
  const editorTransformAfterPan = await page.locator(".image-window").evaluate((element) => element.style.transform);
  expect(editorTransformAfterPan).not.toBe(editorTransformBeforePan);
  const moveSurface = page.getByRole("button", { name: "Move region rectangle" });
  const middleSurfaceBox = await moveSurface.boundingBox();
  expect(middleSurfaceBox).not.toBeNull();
  const draftBeforeMiddle = await page.locator(".slice-draft").boundingBox();
  expect(draftBeforeMiddle).not.toBeNull();
  await page.mouse.move(middleSurfaceBox!.x + middleSurfaceBox!.width / 2, middleSurfaceBox!.y + middleSurfaceBox!.height / 2);
  const transformBeforeMiddle = await page.locator(".image-window").evaluate((element) => element.style.transform);
  await page.mouse.down({ button: "middle" });
  await page.mouse.move(middleSurfaceBox!.x + middleSurfaceBox!.width / 2 + 52, middleSurfaceBox!.y + middleSurfaceBox!.height / 2 + 36);
  await page.mouse.up({ button: "middle" });
  const transformAfterMiddle = await page.locator(".image-window").evaluate((element) => element.style.transform);
  const draftAfterMiddle = await page.locator(".slice-draft").boundingBox();
  expect(draftAfterMiddle).not.toBeNull();
  expect(transformAfterMiddle).not.toBe(transformBeforeMiddle);
  expect(draftAfterMiddle!.width).toBeCloseTo(draftBeforeMiddle!.width, 4);
  expect(draftAfterMiddle!.height).toBeCloseTo(draftBeforeMiddle!.height, 4);
  const transformDelta = transformValues(transformAfterMiddle).map((value, index) => value - transformValues(transformBeforeMiddle)[index]);
  expect(draftAfterMiddle!.x - draftBeforeMiddle!.x).toBeCloseTo(transformDelta[0], 4);
  expect(draftAfterMiddle!.y - draftBeforeMiddle!.y).toBeCloseTo(transformDelta[1], 4);
  await expect(page.locator(".slice-draft > span")).toHaveText(editorDraftSize!);
  const draftBeforeMove = await page.locator(".slice-draft").evaluate((element) => ({ left: element.style.left, top: element.style.top }));
  const moveBox = await moveSurface.boundingBox();
  expect(moveBox).not.toBeNull();
  await page.mouse.move(moveBox!.x + moveBox!.width / 2, moveBox!.y + moveBox!.height / 2);
  await page.mouse.down();
  await page.mouse.move(moveBox!.x + moveBox!.width / 2 + 24, moveBox!.y + moveBox!.height / 2 + 18);
  await page.mouse.up();
  await expect.poll(() => page.locator(".slice-draft").evaluate((element) => ({ left: element.style.left, top: element.style.top }))).not.toEqual(draftBeforeMove);
  await expect(page.locator(".slice-draft > span")).toHaveText(editorDraftSize!);
  const draftSize = await page.locator(".slice-draft > span").textContent();
  const rightHandle = page.getByRole("button", { name: "Resize region right edge" });
  const handleBox = await rightHandle.boundingBox();
  expect(handleBox).not.toBeNull();
  await page.mouse.move(handleBox!.x + handleBox!.width / 2, handleBox!.y + handleBox!.height / 2);
  await page.mouse.down();
  await page.mouse.move(handleBox!.x + handleBox!.width / 2 + 50, handleBox!.y + handleBox!.height / 2);
  await page.mouse.up();
  await expect.poll(() => page.locator(".slice-draft > span").textContent()).not.toBe(draftSize);
  await page.getByRole("button", { name: "Cancel region" }).click();
  await expect(page.locator(".slice-draft")).toHaveCount(0);
  expect(errors).toEqual([]);
});
