import { test, expect } from "@playwright/test";
import { cp, rm } from "node:fs/promises";
import path from "node:path";

const fixtureRoot = path.resolve("tests/fixtures/projects");
const projectsRoot = path.resolve("test-results/projects");
const transformValues = (value: string) => value.match(/translate\(([-\d.]+)px, ([-\d.]+)px\) scale\(([-\d.]+)\)/)!.slice(1).map(Number);
const expectTransform = (actual: number[], expected: number[]) => expected.forEach((value, index) => expect(actual[index]).toBeCloseTo(value, 5));

test.beforeEach(async () => {
  await rm(projectsRoot, { recursive: true, force: true });
  await cp(fixtureRoot, projectsRoot, { recursive: true });
});

test("preserves full-image transform when selecting YAML slice", async ({ page }) => {
  const errors: string[] = [];
  page.on("pageerror", (error) => errors.push(error.message));
  page.on("console", (message) => { if (message.type() === "error") errors.push(message.text()); });
  await page.goto("/");
  expect(errors).toEqual([]);
  const root = page.getByRole("treeitem", { name: "scan-01" });
  await expect(root).toHaveAttribute("aria-checked", "true");
  await expect(page.getByRole("heading", { name: "scan-01" })).toBeVisible();
  await expect(page.locator("img.document")).toBeVisible();
  await expect.poll(() => page.locator(".image-window").evaluate((element) => ({ width: element.style.width, height: element.style.height }))).toMatchObject({ width: "1200px", height: "800px" });
  await page.getByRole("button", { name: "Actual Size" }).click();
  const viewer = page.locator(".viewer");
  const imageBox = await page.locator(".image-window").boundingBox();
  const viewerBox = await viewer.boundingBox();
  expect(imageBox).not.toBeNull();
  expect(viewerBox).not.toBeNull();
  const imagePoint = (x: number, y: number) => ({ x: imageBox!.x - viewerBox!.x + x, y: imageBox!.y - viewerBox!.y + y });
  await viewer.hover({ position: imagePoint(120, 100) });
  await page.mouse.down();
  await page.mouse.move(imageBox!.x + 80, imageBox!.y + 70);
  await page.mouse.up();
  await expect(page.locator(".zoom-readout")).toHaveText("100%");
  await viewer.hover({ position: imagePoint(220, 180) });
  await page.mouse.wheel(0, -200);
  await expect(page.locator(".zoom-readout")).toHaveText("112%");
  const transformBeforeSlice = await page.locator(".image-window").evaluate((element) => element.style.transform);
  expect(transformBeforeSlice).toMatch(/^translate\([^)]*\) scale\(1\.12\)$/);
  await page.getByRole("button", { name: /Slice/ }).click();
  await page.evaluate(() => new Promise<void>((resolve) => requestAnimationFrame(() => requestAnimationFrame(() => requestAnimationFrame(() => resolve())))));
  await expect(page.getByText("Drag over image to draw slice")).toBeVisible();
  await expect(page.locator(".zoom-readout")).toHaveText("112%");
  await expect.poll(() => page.locator(".image-window").evaluate((element) => element.style.transform)).toBe(transformBeforeSlice);
  await page.getByRole("treeitem", { name: "scan-01" }).locator(".tree-project-label").click();
  await expect(page.getByText("Drag over image to draw slice")).toHaveCount(0);
  await expect(page.locator(".image-window.crop-window")).toHaveCount(0);
  await page.getByRole("button", { name: /Slice/ }).click();
  await expect(page.getByText("Drag over image to draw slice")).toBeVisible();
  await page.getByText("Receipt", { exact: true }).click();
  await expect(page.getByText("Drag over image to draw slice")).toHaveCount(0);
  await page.evaluate(() => new Promise<void>((resolve) => requestAnimationFrame(() => requestAnimationFrame(() => requestAnimationFrame(() => resolve())))));
  await expect(page.locator(".image-window.crop-window")).toBeVisible();
  await expect.poll(() => page.locator(".image-window.crop-window").evaluate((element) => ({ width: element.style.width, height: element.style.height }))).toMatchObject({ width: "420px", height: "260px" });
  await expect(page.locator("img.document")).toBeVisible();
  const cropFit = await page.evaluate(() => { const viewer = document.querySelector<HTMLElement>(".viewer")!; const scale = Math.max(0.15, Math.min(1, Math.min((viewer.clientWidth - 64) / 420, (viewer.clientHeight - 64) / 260))); return [(viewer.clientWidth - 420 * scale) / 2, (viewer.clientHeight - 260 * scale) / 2, scale]; });
  const cropTransform = await page.locator(".image-window.crop-window").evaluate((element) => element.style.transform);
  expectTransform(transformValues(cropTransform), cropFit);
  expect(cropTransform).not.toBe(transformBeforeSlice);
  await page.getByRole("treeitem", { name: "scan-01" }).locator(".tree-project-label").click();
  await expect(page.locator(".image-window.crop-window")).toHaveCount(0);
  const rootFit = await page.evaluate(() => { const viewer = document.querySelector<HTMLElement>(".viewer")!; const scale = Math.max(0.15, Math.min(1, Math.min((viewer.clientWidth - 64) / 1200, (viewer.clientHeight - 64) / 800))); return [(viewer.clientWidth - 1200 * scale) / 2, (viewer.clientHeight - 800 * scale) / 2, scale]; });
  const rootTransform = await page.locator(".image-window").evaluate((element) => element.style.transform);
  expectTransform(transformValues(rootTransform), rootFit);
  await viewer.hover({ position: { x: 30, y: 30 } });
  await page.mouse.down({ button: "middle" });
  await page.mouse.move(94, 78);
  await page.mouse.up({ button: "middle" });
  await expect.poll(() => page.locator(".image-window").evaluate((element) => element.style.transform)).not.toBe(rootTransform);
  await page.getByRole("button", { name: "Edit Receipt" }).click();
  const editorTransformBeforePan = await page.locator(".image-window").evaluate((element) => element.style.transform);
  const editorDraftSize = await page.locator(".slice-draft > span").textContent();
  const editorViewerBox = await viewer.boundingBox();
  expect(editorViewerBox).not.toBeNull();
  await page.keyboard.down("Space");
  await viewer.hover({ position: { x: 24, y: 24 } });
  await page.mouse.down();
  await page.mouse.move(editorViewerBox!.x + 64, editorViewerBox!.y + 52);
  await page.mouse.up();
  await page.keyboard.up("Space");
  const editorTransformAfterPan = await page.locator(".image-window").evaluate((element) => element.style.transform);
  expect(editorTransformAfterPan).not.toBe(editorTransformBeforePan);
  const moveSurface = page.getByRole("button", { name: "Move slice rectangle" });
  const middleSurfaceBox = await moveSurface.boundingBox();
  expect(middleSurfaceBox).not.toBeNull();
  const draftBeforeMiddle = await page.locator(".slice-draft").boundingBox();
  expect(draftBeforeMiddle).not.toBeNull();
  await page.mouse.move(middleSurfaceBox!.x + middleSurfaceBox!.width / 2, middleSurfaceBox!.y + middleSurfaceBox!.height / 2);
  const transformBeforeMiddle = await page.locator(".image-window").evaluate((element) => element.style.transform);
  await page.mouse.down({ button: "middle" });
  await page.mouse.move(middleSurfaceBox!.x + middleSurfaceBox!.width / 2 + 52, middleSurfaceBox!.y + middleSurfaceBox!.height / 2 + 36);
  await page.mouse.up({ button: "middle" });
  const transformAfterMiddle = await page.locator(".image-window").evaluate((element) => element.style.transform);
  const draftAfterMiddle = await page.locator(".slice-draft").boundingBox();
  expect(draftAfterMiddle).not.toBeNull();
  expect(transformAfterMiddle).not.toBe(transformBeforeMiddle);
  expect(draftAfterMiddle!.width).toBeCloseTo(draftBeforeMiddle!.width, 4);
  expect(draftAfterMiddle!.height).toBeCloseTo(draftBeforeMiddle!.height, 4);
  const transformDelta = transformValues(transformAfterMiddle).map((value, index) => value - transformValues(transformBeforeMiddle)[index]);
  expect(draftAfterMiddle!.x - draftBeforeMiddle!.x).toBeCloseTo(transformDelta[0], 4);
  expect(draftAfterMiddle!.y - draftBeforeMiddle!.y).toBeCloseTo(transformDelta[1], 4);
  await expect(page.locator(".slice-draft > span")).toHaveText(editorDraftSize!);
  const draftBeforeMove = await page.locator(".slice-draft").evaluate((element) => ({ left: element.style.left, top: element.style.top }));
  const moveBox = await moveSurface.boundingBox();
  expect(moveBox).not.toBeNull();
  await page.mouse.move(moveBox!.x + moveBox!.width / 2, moveBox!.y + moveBox!.height / 2);
  await page.mouse.down();
  await page.mouse.move(moveBox!.x + moveBox!.width / 2 + 24, moveBox!.y + moveBox!.height / 2 + 18);
  await page.mouse.up();
  await expect.poll(() => page.locator(".slice-draft").evaluate((element) => ({ left: element.style.left, top: element.style.top }))).not.toEqual(draftBeforeMove);
  await expect(page.locator(".slice-draft > span")).toHaveText(editorDraftSize!);
  const draftSize = await page.locator(".slice-draft > span").textContent();
  const rightHandle = page.getByRole("button", { name: "Resize slice right edge" });
  const handleBox = await rightHandle.boundingBox();
  expect(handleBox).not.toBeNull();
  await page.mouse.move(handleBox!.x + handleBox!.width / 2, handleBox!.y + handleBox!.height / 2);
  await page.mouse.down();
  await page.mouse.move(handleBox!.x + handleBox!.width / 2 + 50, handleBox!.y + handleBox!.height / 2);
  await page.mouse.up();
  await expect.poll(() => page.locator(".slice-draft > span").textContent()).not.toBe(draftSize);
  await page.getByRole("button", { name: "Cancel slice" }).click();
  await expect(page.locator(".slice-draft")).toHaveCount(0);
  await page.getByRole("button", { name: "Edit Receipt" }).click();
  await page.getByRole("button", { name: "Resize slice bottom edge" }).click();
  await page.getByRole("button", { name: "Confirm slice" }).click();
  await expect(page.locator(".slice-draft")).toHaveCount(0);
  expect(errors).toEqual([]);
});
